<?php
/**
 * Copyright © Àngel Díaz, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
 /**
  * @see \Angeldm\Cockpit\Block\Adminhtml\System\Cockpit
  */
?>
<?php if ($block->isEnabled()) : ?>
    <?php if ($block->ping()) : ?>
      <div class="dashboard-container row">
        <div class="dashboard-main col-m-12">
          <div class="row">
            <iframe
              style="width: 100%;
                width: -webkit-fill-available;
                height: 700px;
              "src="<?= $block->escapeHtml($block->getCockpitURL()) ?>"></iframe>
            </div>
          </div>
        </div>
      <?php else: ?>
        <div class="alert">
            Server not respond
        </div>
    <?php endif; ?>
<?php else: ?>
  <div class="alert">
      Cockpit not enabled
  </div>
<?php endif; ?>
