<?php
/** @var $block \Company\Module\Block\Adminhtml\Question\Grid\Switcher */
?>
<?php if ($links = $block->getLinks()): ?>
<div class="store-switcher store-view">
    <div class="actions dropdown closable">
        <button
                type="button"
                class="admin__action-dropdown"
                data-mage-init='{"dropdown":{}}'
                data-toggle="dropdown"
                aria-haspopup="true"
                id="grid-change-button">
            <?= /* @escapeNotVerified */
                $block->getCurrentGridTitle() ?>
        </button>
        <ul class="dropdown-menu" data-role="grid-list">
            <?php foreach ($links as $link): ?>
            <li><?= __($link['title']) ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>
