<?php

if ($this->getDashboard()) {
    if (!$this->isEnabled()) {
        ?>
      <h>Cockpit not enabled</h>
    <?php
    } else {
        if ($this->ping() != 200) {
            ?>
        <h>Cockpit not ping</h>
        <?php
        } else {
            ?>

            <div>
                      <iframe
                          name="logs" style=" width: -webkit-fill-available; height: -webkit-fill-available; pointer-events: none;"
                          src="https://<?= $this->getHost() ?>:<?= $this->getPort() ?>/cockpit/@localhost/system/index.html" ></iframe>
                      </div>








          <?php
        }
    }
}?>
