

  <?php   if ($this->isEnabled()) {
    if ($this->ping() != 200) {
        ?>
          <h>Cockpit not ping</h>
          <?php
    } else {
        ?>
            <iframe width="800px" height="600px"
              src="https://<?= $this->getHost() ?>:<?= $this->getPort() ?>/cockpit/@localhost/system/terminal.html"
              style="
    width: -webkit-fill-available;
    height: -webkit-fill-available;
" />
            <?php
    }
} else {
    ?>
      <h>Cockpit not enabled</h>
<?php
} ?>
